-- Migration: Fix Schema Mismatches
-- Generated by Antigravity
-- Date: 2024-12-17

-- 1. Modify public.matches
-- We need to alter the ID type which is complex if there is existing data. 
-- Assuming 'id' is bigint, changing to UUID is hard without dropping. 
-- For this "fix", I will Drop and Recreate because the user said "fresh database schema" meaning likely empty or dev.

DROP TABLE IF EXISTS public.matches CASCADE;

CREATE TABLE public.matches (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    league text NOT NULL,
    home_team jsonb NOT NULL,
    away_team jsonb NOT NULL,
    start_time timestamp with time zone NOT NULL,
    is_live boolean DEFAULT false,
    status text DEFAULT 'scheduled'::text,
    home_score integer,
    away_score integer,
    winner text,
    questions jsonb DEFAULT '[]'::jsonb, -- Stores flexible questions with option_ids
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Modify public.pools
-- Dropping and recreating to ensure clean state for new columns and constraints.

DROP TABLE IF EXISTS public.pools CASCADE;

CREATE TABLE public.pools (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text NOT NULL, -- Renamed from title
    description text,
    image_url text,
    tier text NOT NULL CHECK (tier IN ('Bronze', 'Silver', 'Gold', 'Platinum')), -- Case sensitive match to frontend? Frontend said 'Bronze', Schema said 'bronze'. Using Title Case.
    entry_fee integer NOT NULL CHECK (entry_fee IN (5, 25, 50, 100)),
    max_participants integer,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status text DEFAULT 'upcoming'::text CHECK (status IN ('ongoing', 'upcoming', 'ended')), -- Matching frontend literal types
    total_pot numeric DEFAULT 0,
    rules text,
    prize_distribution jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. Create public.pool_participants

CREATE TABLE IF NOT EXISTS public.pool_participants (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    pool_id uuid NOT NULL REFERENCES public.pools(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    joined_at timestamp with time zone DEFAULT now(),
    UNIQUE(pool_id, user_id)
);

-- 4. Create public.bets

CREATE TABLE IF NOT EXISTS public.bets (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    match_id uuid NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    question_id text NOT NULL, -- ID from the question JSON
    option_id text NOT NULL,   -- ID from the specific option in JSON
    amount numeric NOT NULL CHECK (amount > 0),
    potential_payout numeric,
    status text DEFAULT 'pending'::text CHECK (status IN ('pending', 'won', 'lost', 'void')),
    created_at timestamp with time zone DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_bets_user_id ON public.bets(user_id);
CREATE INDEX IF NOT EXISTS idx_bets_match_id ON public.bets(match_id);
CREATE INDEX IF NOT EXISTS idx_pool_participants_user_id ON public.pool_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_matches_start_time ON public.matches(start_time);
